# Generated by Django 2.2.3 on 2019-07-23 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrackingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DefaultModelValue', max_length=200)),
                ('status', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('recoveredHashes', models.IntegerField()),
                ('totalLoadedHashes', models.IntegerField()),
                ('triedPasswords', models.IntegerField()),
                ('totalPasswords', models.IntegerField()),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('hashType', models.IntegerField()),
                ('attackMode', models.IntegerField()),
                ('sessionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashText', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('crackingTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashcat.CrackingTask')),
            ],
        ),
    ]
